### ISSUE TITLE
Label's adjustsFontSizeToFitWidth does not work 

### ISSUE THREAD

**Issue by oferRounds** [TTTAttributedLabel/TTTAttributedLabel#606] opened 2015-11-14 23:48 UTC
I use the following code:

`TTAttributedLabel *label = [[TTTAttributedLabel alloc] initWithFrame:frame];`
`label.adjustsFontSizeToFitWidth = YES;`
`label.minimumScaleFactor = 0.1;`
    
`label.attributedText = <some attributed string>`
`label.verticalAlignment = TTTAttributedLabelVerticalAlignmentTop;`
`label.lineBreakMode = NSLineBreakByWordWrapping;`
`label.numberOfLines = 5;`

but the text does not get adjusted when there's not enough space.
Is it maybe because I use an attributed string?

**Comment by christophercotton** [comment] 2016-01-19 22:27
See this issue:  https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/564

**Comment by jessesquires** [comment] 2016-01-20 01:33
Thanks @oferRounds / @christophercotton! :smile: 

Closing as dupe of #564

**Closed by jessesquires** 2016-01-20 01:33 UTC
Labels: duplicate

**Comment by oferRounds** [comment] 2016-01-20 09:16
:+1:
