### ISSUE TITLE
link color not working on iOS 8

### ISSUE THREAD

**Issue by weakfl** [TTTAttributedLabel/TTTAttributedLabel#497] opened 2015-02-05 16:06 UTC
Link colors are working fine on iOS 7, but are not displayed on iOS 8.
I'm setting the link attributes like this:
```objective-c
_lblFooter.linkAttributes = @{ NSForegroundColorAttributeName: [UIColor colorWithRed:151.0f/255.0f green:191.0f/255.0f blue:13.0f/255.0f alpha:1.0f], NSUnderlineStyleAttributeName: [NSNumber numberWithInt:NSUnderlineStyleSingle] };
```

**Comment by jhersh** [comment] 2015-02-05 16:19
Try `(id)kCTForegroundColorAttributeName`.

**Comment by weakfl** [comment] 2015-02-05 16:40
Working on iOS 8 (and 7).
Thanks a lot!

**Comment by renatosc** [comment] 2015-02-14 08:45
Same problem here.  Using kCTForegroundColorAttributeName worked. Thanks!

**Comment by Ricardo1980** [comment] 2015-04-02 15:41
What is the reason of this? Should I also use kCTForegroundColorAttributeName for iOS7? Thanks in advance.

**Comment by ParilShah** [comment] 2015-04-07 20:30
I have written below code for setting link Attributes, 
termsAndPrivacy.linkAttributes = @{ (id)kCTUnderlineStyleAttributeName: [NSNumber numberWithInt:NSUnderlineStyleSingle],
		                                (id)kCTForegroundColorAttributeName: [UIColor lightGrayColor] };

Strange!! works perfect in iOS 7 but in iOS 8 it takes Thick lines though I have set Underline Style as a single. For reference, see attached screenshot, refer RED block, it is designed with TTTAttributedLabel.
![tttattributedlabel](https://cloud.githubusercontent.com/assets/3435334/7032800/d7b15d68-dd92-11e4-8346-b055636aed2b.png)

**Comment by rsanchezsaez** [comment] 2015-05-06 17:40
In my opinion this looks like a regression, and `NSForegroundColorAttributeName` should be fixed again, regardless of the`(id)kCTForegroundColorAttributeName` workaround.

The "*this is a a drop-in replacement for UILabel*" part of the tagline is less and less true by the day.

**Comment by jhersh** [comment] 2015-05-06 18:21
TTTAttributedLabel is a project maintained by volunteers. Part of the :star2: of open-source is that all the internals are laid bare for all to see. I would welcome pull requests or constructive comments from the community to address this issue.

**Comment by rsanchezsaez** [comment] 2015-05-06 18:51
Sorry if my message sounded harsh, it wasn't my intention! I appreciate the work on the project. If I got around to fixing this, I'll submit a pull request.

Do you happen to know which change made this stop working? Is this a general problem with all `NS*` attributes or does it only affect some of them?

**Comment by jhersh** [comment] 2015-05-06 20:30
I don't see a single reference to `NSForegroundColorAttributeName` anywhere in the label. Some cursory git-blaming suggests that this dates from at least March 2013.

These attributes are not equivalent, so we'd probably need to update every reference to `(id)kCTForegroundColorAttributeName` to also allow for the existence of `NSForegroundColorAttributeName`; perhaps also with other CT/UI attribute pairs.

**Comment by rsanchezsaez** [comment] 2015-05-07 09:30
We're currently using 1.10.1, which was released on Jun 12, 2014 and `NSForegroundColorAttributeName` works there.

Maybe before it was using the `NSAttributedString` draw methods, which implicitly use its attributes, and that's not the case now.

**Comment by rsanchezsaez** [comment] 2015-05-07 16:00
Actually I'm wrong, vanilla 1.10.1 doesn't have `NSForegroundColorAttributeName` working. We have it working as the side-effect of some old changes we did. Sorry about the noise.

**Comment by RobertBiehl** [comment] 2015-07-30 10:57
:+1:

**Comment by galambalazs** [comment] 2015-09-14 09:29
I think this can be closed because my PR fixed it: https://github.com/TTTAttributedLabel/TTTAttributedLabel/pull/549

Merged in: https://github.com/TTTAttributedLabel/TTTAttributedLabel/commit/9bc779e734fed557c927df8c3a45d6964520c99c

cc @getaaron

**Comment by getaaron** [comment] 2015-09-14 14:57
:+1:

**Closed by getaaron** 2015-09-14 14:57 UTC
