### ISSUE TITLE
Text doesn't display with long strings.

### ISSUE THREAD

**Issue by andrewbradnan** [TTTAttributedLabel/TTTAttributedLabel#568] opened 2015-08-11 22:08 UTC
Is there a maximum string we can use with this control?  I've been displaying some log files, which run very long in some cases and above some size, all the text disappears.  I've made sure I have nice ascii only text to display, add no links, etc. as boring a case as I can and it still happens.  .text or .attributedText doesn't seem to matter. I do get a sizeThatFits() back that is fine.

The last string that I tried was 12,107 characters, 97 lines, and had a height of 8,260 but displayed nothing.

Any suggestions?  Thanks

**Comment by getaaron** [comment] 2015-08-11 22:59
I don't know of a specific max length off the top of my head, but I recall running into a similar issue. Possible workarounds are using multiple labels, using `UITextView`, etc.

If you can narrow this down more (i.e. find the exact cutoff point where it stops working) we might be able to resolve the issue or at least document it.

**Comment by getaaron** [comment] 2015-08-24 22:46
@andrewbradnan Are you able to provide specific reproduction steps, or perhaps write a failing test?

**Comment by getaaron** [comment] 2015-09-12 20:58
Closing due to lack of reproduction steps - @andrewbradnan, if you're able to write some, please open a new issue following the [contribution guidelines](https://github.com/TTTAttributedLabel/TTTAttributedLabel/blob/master/CONTRIBUTING.md).

**Closed by getaaron** 2015-09-12 20:58 UTC
