### ISSUE TITLE
attributedText is not loaded from Interface Builder

### ISSUE THREAD

**Issue by tamastimar** [TTTAttributedLabel/TTTAttributedLabel#509] opened 2015-03-09 16:36 UTC
I've a label in Interface Builder with attributed text. Its class is set to `TTTAttributedLabel`. Despite that, the attributes set in IB are not visible (e.g. some part of the text is bold).

After some debugging it seems that the following code is not reached:
```objective-c
- (id)initWithCoder:(NSCoder *)coder {
// ...
    if ([coder containsValueForKey:NSStringFromSelector(@selector(attributedText))]) {
        self.attributedText = [coder decodeObjectForKey:NSStringFromSelector(@selector(attributedText))];
    } 
// ...
}
```
Instead of that it just grabs the `text` property of label in else branch.

I'm using Xcode 6.1.1, base SDK is iOS 8.1.

**Comment by jhersh** [comment] 2015-03-09 22:34
> Instead of that it just grabs the text property of label in else branch.

Assigning to the `text` property does internally assign to the `attributedText` property after an attributed string has been created. I'm not so sure that's what the problem is here; instead, I think it's more likely that the problem is what you've noted in #464: `TTTAttributedLabel`'s current architecture requires that `text` is assigned after all other relevant styling properties have been assigned, and we simply cannot guarantee that order of operations with `IBInspectable`. 

I'd be interested to hear if this is any better with today's Xcode 6.2 release. If not, I don't know that `IBInspectable` is yet suitable for use with `TTTAttributedLabel`.

**Comment by tamastimar** [comment] 2015-03-10 08:29
In this issue `IBInspectable` properties **are not involved** at all, so I think its not connected to #464.

Am I wrong about that the purpose of the snippet above is to fill properties from XIB/Storyboard?

It's not changed with iOS 8.2/Xcode 6.2.

_(I've commented the `IBInspectable` finding to #464 because I believe that's the root problem. If label would be redrawn when any of properties are changed than it would work. So for the clarity I'd open another issue for `IBInspectable` bug. Is that OK?)_

**Comment by tamastimar** [comment] 2015-03-10 13:14
And here is a screenshot about the problem:

![tttattributedlabel-ib](https://cloud.githubusercontent.com/assets/7582344/6575523/b8528e70-c72f-11e4-99a0-18e0088975f3.png)

**Comment by jhersh** [comment] 2015-03-10 17:31
You should not assign anything directly to the `attributedText` property. As above, it is internally assigned to when the `text` property changes. Perhaps instead we should try adding the `IBInspectable` annotation to TTTAttributedLabel's redeclaration of the `text` property?

**Comment by jhersh** [comment] 2015-06-15 18:19
Looks like IB problems with custom views will be around for a while longer. I did mark the `text` override as `IBInspectable`, but I don't know that issues like this one are fixable on our end without improved tooling. Closing for now.

**Closed by jhersh** 2015-06-15 18:19 UTC
