### ISSUE TITLE
Usage in IB gives error messages but app works

### ISSUE THREAD

**Issue by aiQon** [TTTAttributedLabel/TTTAttributedLabel#460] opened 2014-11-21 11:39 UTC
Hi,
I tried to use this library/component for its link-ability.
I added it as a Pod. This works without problems.

One of my projects needs to have touchable words in a UILabel. The view hosting this UILabel is designed in a xib.

I tried to set the Class of the UILabel to TTTAttributedLabel, because it seems to support IB_DESIGNABLE and the respective Inspectables.

The Inspectable attributes appear in the attributes inspector and the app compiles and runs fine.

I just have nasty error message which I dont quiet get:

![screen shot 2014-11-21 at 12 37 54](https://cloud.githubusercontent.com/assets/514460/5141854/4842cd84-717b-11e4-8a56-8ac6d7726f06.png)
![screen shot 2014-11-21 at 12 38 35](https://cloud.githubusercontent.com/assets/514460/5141859/55453e40-717b-11e4-9172-73e173ab1c27.png)

They seem just to be about the component to fail being renderable inside Interface Builder. If thats the case, how to disable these errors? If its more than that I would appreciate help to get rid of them.

Thanks in advance.

**Comment by pyraego** [comment] 2015-01-03 05:15
Same issue! Rollback removed error.

**Comment by jhersh** [comment] 2015-01-03 20:40
Thanks everyone, it is understood there is an issue here. The +1s are not helping. :)

Apple's [IB Objects documentation](https://developer.apple.com/library/ios/recipes/xcode_help-IB_objects_media/chapters/CreatingaLiveViewofaCustomObject.html#//apple_ref/doc/uid/TP40014224-CH41-SW1) is not particularly revealing here. As others have suggested, this may be an Xcode bug.

This is a blocking issue for some people - it prevents projects from compiling. I would propose removing the `IB_DESIGNABLE` and `IBInspectable` attributes from the label until Xcode is updated or the label can be made to render a preview in an IB document (or both). Any thoughts here @mattt?

**Comment by mattt** [comment] 2015-01-04 07:30
@jhersh If this is indeed causing projects not to compile anymore, than by all means—revert 38b960763dbd3a106cb291d1cbcf7e95f8cfe057. It was my understanding that this was more a cosmetic annoyance than an actual error.

**Comment by jhersh** [comment] 2015-01-04 19:15
Ah, my mistake - it does show several warnings `(Failed to load designables from path (null))` but the project does still compile. We'll leave them in for now.

**Comment by nebiros** [comment] 2015-01-13 21:49
+1, same issue. The project compiles BTW.

**Comment by jhersh** [comment] 2015-01-22 05:53
These IB errors may be related to using TTTAttributedLabel as a static library: https://github.com/CocoaPods/CocoaPods/issues/2792

You can instead import TTTAttributedLabel as a dynamic framework today with the CocoaPods `0.36` beta and `use_frameworks!` added to your `Podfile`.

**Comment by jhersh** [comment] 2015-02-11 01:48
Closing as this is not a problem with TTTAttributedLabel. A CocoaPods workaround is available.

**Comment by Fl0p** [comment] 2015-02-26 16:50
Any other solution ? except ```use_frameworks``` ?
I can't use it because of other error
```The 'Pods-App' target has transitive dependencies that include static binaries: %a list of pods with static libs%```

Can we add some changes in project structure and settings to show IB path to a fake module ??

**Comment by sabicad** [comment] 2015-03-25 10:06
I found the solution with adding additional valid architectures to project. So, now my architectures are "arm64 armv7 armv7s"

**Comment by drekka** [comment] 2015-05-13 08:16
Updating cocoa pods doesn't work if you are supporting iOS7. Cannot use frameworks. We actually need to get this fixed as without working IBDesignables, many of our UIs are difficult to work in in IB.

**Comment by Fl0p** [comment] 2015-05-13 08:51
Agreed with @drekka 
Dynamic frameworks are not supported by ios7 - http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/#Availability

@jhersh 
it is preatty simple to allow user to chose with some #ifdef

```
#ifndef REMOVE_IB_DESIGNABLE
IB_DESIGNABLE
#endif
```
So it will allow to disable IB_DESIGNABLE/IBInspectable support

**Comment by jhersh** [comment] 2015-05-13 19:29
Let's be very clear here about the problem, which is that you cannot use `IB_DESIGNABLE` or `IBInspectable` in a static library. This is emphatically not a bug with `TTTAttributedLabel`; instead, the bug is entirely Apple's.

We have at least two workarounds:
- Install `TTTAttributedLabel` as a dynamic framework, e.g. with CocoaPods 0.36 and newer. (requires iOS 8)
- Install `TTTAttributedLabel` by dragging its source files to your project (no CocoaPods required)

@Fl0p has a suggestion for a third workaround, which would conditionally remove `IB_DESIGNABLE` and `IBInspectable` with the addition (or absence) of a preprocessor `#define`. Is there broad support for this third option? If so, I'd be okay adding it.

**Comment by Fl0p** [comment] 2015-05-14 14:21
:+1:

**Comment by jhersh** [comment] 2015-05-14 16:57
Thoughts on #529?

**Comment by hagile** [comment] 2015-05-16 06:38
I've drag & drop TTTAttributedLabel classes in my project, and created an outlet for it. Its working fine, but have the same error? How to solve this? Is there any workaround for this? @jhersh @mattt

**Comment by re7ty** [comment] 2015-05-22 12:02
Was same ussie, updating CocoaPods to 0.37.1 solved problem!

**Comment by nikhildcodalsystem** [comment] 2015-06-12 15:26
Inherit TTTAttributedLabel to your own class and add Your class in IB.
I think It Works best.

**Comment by SamuraiZack** [comment] 2015-07-08 21:03
I've removed it from my Podfile and manually dragged the classes into my project. Added them into my Objective-C bridging header and now I can use it in IB. Hope that helps!

**Comment by hagile** [comment] 2015-07-13 10:06
@SamuraiZack, how do we add it into bridging header? What's that stuff? :(

**Comment by hagile** [comment] 2015-07-13 10:07
@nikhildcodalsystem, thanks for the tip. I'll bluff my logic as you said  – will update here.

**Comment by jhersh** [comment] 2015-07-13 20:16
If you are experiencing this problem, some workarounds are:

- Install TTTAttributedLabel as a dynamic framework using either
    - Carthage 
    - CocoaPods 0.36+
- Install TTTAttributedLabel by dragging its source files to your project

#529 is one possible longer-term solution. Comments are welcome there!

Locking this for now. :lock:

**Closed** 2015-07-18 00:19 UTC
